return {
  "nvim-treesitter/nvim-treesitter",
  opts = {
    ensure_installed = {
      "bash",
      "html",
      "javascript",
      "json",
      "lua",
      "markdown",
      "markdown_inline",
      "python",
      "query",
      "regex",
      "tsx",
      "css",
      "scss",
      "typescript",
      "vim",
      "yaml",
      "go",
      "gomod",
      "gowork",
      "gosum",
      "liquid",
      "prisma",
    },
    highlight = {
      enable = true,
    },
    indent = { enable = true },
  },
}
